site_logo: /assets/uploads/logo.png
contact_details:
  tel: null
  fax: null
  email: accelerate-science@cst.cam.ac.uk
  address: |-
    Department of Computer Science and Technology\
    William Gates Building\
    15 J J Thomson Avenue\
    Cambridge\
    CB3 0FD
social_details:
  twitter_link: https://twitter.com/AccelerateSci
  facebook_link: https://facebook.com/
  instagram_link: https://instagram.com/
footer_images:
  - image: /assets/uploads/ml-cl.svg
    link: https://mlatcl.github.io/
  - image: /assets/uploads/cambridge-university.png
    link: https://www.cam.ac.uk/
